language: php

php:
  - '7.3'
  - '7.4'

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - travis_retry composer install -n

script:
  - composer test
